travis:
  secure:
    BINSTAR_TOKEN: avSCB+9IYrlMEOeYIMrWVCj12560TUuJOKnR2BJRA8HO0JiadyYYcdM/DZ+Ds9rlOYai6OtZ3pN8RIudQWmXNLsH0SdMmOFZB3hR5aKJ17Qltke6tuZdFaG/W35w5mQNVo5gk4G1yKQ4Ztn9PtfAh3PSkJ/wMYoysM0RwdllN4PJoinXOa2TYkIRiAUOzCpJtk6audB8MO01QlxDV7hpQWrF2KK0uiS8ea3V/iA0Nv5uCNvW1UMygByHZV7kXQP03dlheUMJor5U1VZDrDnkp3upwZUGEGaAEZB9pB7JtnwXV1PyKKLIb10alWyl0kBpvrz/tY0G/eODP+dpuLiZdeoAuAZevcRcNz0ScvSsxGYSgFHAG3nHdQ8IFebncmhzOeYFqT3UdM4dCMC3A35os5JiYWD99EPi3yywmeHTXbDKU09SfGQxTdXusQWBBgKbkNoGzbfJ5L54VDrdYl6bMBePvpJjqJ1gGe8I1kRU2OEd3ZQkx8weG/Y4eoUXIDmH4KyYJk478rLzKGbl0RqZILP31jj7/U23DJE/t6uECIoSdewk8PYjaIePGxKXdELwZWPmoNkUYdxPLwF0IEaB4e4JR2/mtEqKOSE9ya6yL5+1mnQEyHj25bqYUHcSyC7J/A0g3xA9oKwULvx7BqoJ5JGb9IFKFxeKE0q7/HV77HE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
