travis:
  secure:
    BINSTAR_TOKEN: Apiq3cbddDHpW7DWO5MsIEyJOpVopL3VLN+OHCoxhfqIzC8sZXsV1NtdcHN2gmCcKSc54J2Og5a3/XpdGyAtu08v2NRY51U+feiH9ftA4B/2ifqZQUpCmp+BoIxJwZCmBJuh+KtRAOStx+I894ED6beX2k6FwLyRy/XfA/j4hMhLuEpo3wToNqTeSshBxx8gD9SdqWIZim/EuRZMDYB8RAxdPKB+TG0SiB6wUPzCEsGn2a+iOIgY/HlppiPS3I39oo/BBYN7I63yVTAc0MDv8MrbLvQr8mokN++9/ka5KfzG18SPj0sFaBorCBkHtxHz1AF184ZstT2E9k/vWxMbq6TzZzljzgK7Th0HUQR+2QgAYdDiTkYE2GioiotuHEI3J1YWDD7vWpvcYk1nB4HcVbCRNiR74Mgyan5RDjPKpKfBgwIwLH3OvfcWxn2Kr/npWyRQGv1GuN/D/grMuHO45/OYYu87V2MAWUbofcrAbZaSTKxvtYiEl8o2r3s0ljl6oIsEZYXT5J3xxDCAAsuFq0R1k2o04/+n5LBBNwDb2uJufdTaJqGQM33E9ApcjOV11QpqBxgawWD4Lrpp7O1Ov+qz++FtRblOmqtUpdAll9bv1bdbhlgnN4N/Nh2g+QoxzSgd2nT7NZrrOQcNg6MhCLVgV94FEXivj1BxKojL/go=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
