travis:
  secure:
    BINSTAR_TOKEN: mrICYkZODZ/RBdBQWHXEJFzd56D31VHO+mf86asBsRWwx0Dmwa9o2higyWfRp0VykagR7XxYb/3ftuYpaZAUvZnl5yFlgwSaqE10srZbOQJSxVpxweuuahHirAgxMIptD/asgC6d5+d2TSv4TY/OMqhkMcj5+Lml31L9bVySYkdjcwipm0mz5KQlgivk2myLuwvjek7dx0BHqwUZawgth2gYlQZIFtUzea07dvvm31x0hY3MUSartUqsbP9rlz5Y/Ij+kqTEKhdbi8DoY4wUDJ8EUuRTapSRR0IOkLKn8S+sHcr7l7ra0P1cPl1pC6+zdJkypAtrd+k7HLJK5U9wCDh7tbPOTsrYeyNWKzRqbQvr6y/vPyyWB9kx9I81fsCco7NxuZfLkiU6kOVf4MFuEKzkFeZJW00aythXtfAO0OUZKTg91FhjtS7ritlgAy1/jXqDAKC6N8t1QywQagB4w8CVQ0BYbGfXcHhxFqsaIUEcI+Zm3kpbiym20VbvoodfrDBHRN8AIlFULI23L5g0sGRHXe7JMFPRqd42mPNhkJRUTjxsbPP0IUXV/JJoe3ta5wavnVrRV5P7Eq7GoMQkLW5qXAI2x7fFRN/emdliGN/GfZCRZrZ1uuOJQDbcIqfeZJLjPJ/WjUvVwdSCZx2mHaoy02pRlygTrYUAMOM9tIY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
